export { default as Header } from './header/Header'
export { default as Navbar } from './navbar/Navbar'
export { default as About } from './about/About'
export { default as FoodCard } from './foodCards/FoodCard'
export { default as Cta } from './cta/Cta'
export { default as Footer } from './footer/Footer'
